# Generated by Django 3.0.4 on 2020-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('booking_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sign_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'BookingInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('country', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('manager_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'branch_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('worktype', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('country', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField()),
            ],
            options={
                'db_table': 'phonenumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('perNightFee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=100)),
                ('max_guests', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('entire_home', models.BooleanField()),
                ('spark_clean', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('heating', models.BooleanField()),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=10)),
                ('review_date', models.DateField()),
                ('overall_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subordination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'subordination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('join_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
    ]
